name: colorich
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^0.6.0
  cyclop: ^0.5.1
  simple_shadow: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  new_gradient_app_bar: ^0.2.0
  modal_bottom_sheet: ^2.0.0



flutter:

  uses-material-design: true
  assets:
    - images/



  fonts:
    - family: KleeOne
      fonts:
        - asset: assets/fonts/KleeOne-Regular.ttf



